### ISSUE TITLE
[EPIC] Project Improvements

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1089]
Want to get the whole projects experience to be improved.

Add related tickets below:
- [x] generating slugs #828
- [ ] project index page redesign #797
- [x] get mention/link for slack room #770 
- [x] CI links on the project page #762
- [ ] Project List Sort Order #763

The tickets above are just a piecemeal of issues - it would be nice to look at the complete project flow experience as we have done with the events EPIC

**Comment by weedySeaDragon** [comment]
Was project sort order addressed by #1458 ? at least in part, perhaps?

**Comment by weedySeaDragon** [comment]
#770 **get mention of which slack chat room to go to on every project page**   might be part this epic, too

**Comment by mattlindsey** [comment]
I think this is done.
