### ISSUE TITLE
[EPIC] Accessibility of Pairing Sessions

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1157]
Anecdotal evidence suggests that MOOC students find it difficult to access pairing sessions.  There are also situations where new members are trying to accesss project pairing and scrum events and have trouble.
## Creation of hangouts
- involves sign in/up
  - [ ] Should we support GitHub login without public emails? #1093
  - [ ] allow email sign up
- requires creating new event
  - ideas: 
    - new event button prominent enough?
    - event spam?
    - [ ] cleaner URL (#988)
- impromptu hangout creation --> should that spawn an event?
## Joining hangouts
- browse pairing events 
  - ideas: 
    - [x] provide link to creator (remove redundant date stuff) (#1133)
    - big list difficult to browse
      - filtering
        - [ ] automate the updating of the list when user selects
      - sorting
      - breaking up the list
      - tagging
      - say how many hours from now an event is 
      - event types shown more clearly
    - [ ] provide link to project (#796)
  - display the project name
  - add nice features from past events? 
    - mouse over colors the event box
    - showing who is in which hangout ...
  - spend time on improving css, layout, coloring
- joining the event
  - want to make live events noticeable and joinable
    - [ ] hold active events in the main event list?
    - [ ] show accurately who is in the event
    - [ ] stale pages means people might not be aware event is live etc.
- Notifications
  - improvements in formatting
  - could bots update the existing slack/gitter links with status?
- making the event fun
  - matching people based on some criterion
  - providing an AI bot
  - play music - pairing playlist?
- Follow up
  - survey and feedback at the end in order to rate pairing sessions --> users ? 
## Data Analysis
- inaccurate data since participants updated to last snapshot
- can updates come from hangoutconnection on join and leave
