### ISSUE TITLE
improve pairing participants identity tracking

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1197]
currently most pair participants g+ does not link up with our local AV membership

**Comment by tansaku** [comment]
* [ ] G+ link up might improve if we give more credit for participating in hangouts #1290 potentially helps here
* [ ] perhaps more importantly we need more people to be aware of karma
  - [ ] linking karma number to breakdown on user page
  - [ ] breakdown on user page is hidden in sub-tab
  - [ ] breakdown doesn't look so nice
  - [ ] need to mail members about their karma scores?  slack ping them?
  - [ ] tooltips to explain things
