### ISSUE TITLE
Improve filtering options for upcoming events

### ISSUE THREAD

**Issue by c1505** [AgileVentures/WebsiteOne#1332]
I can add more details later.  First wanted it open to discuss if these are all desirable things to do. 
- [ ] Change dropdown for upcoming events filter to only include projects that have an upcoming event #1336
- [ ] Filter upcoming events by 169.1 and 169.2 #1337
- [ ] Add filter to upcoming events to select between scrum and pair programming #1338
- [ ] Remove inactive recurring events with code or manually #1339

As a user
On the upcoming events page
I want the dropdown for projects to filter from to only include projects that have an upcoming event
So that I don't see projects that don't have a current event
So that I can find the event I am interested in

As a student of CS169
On the upcoming events page
I want to be able to filter to only see pair programming events for my class
So that i can find a pairing partner easily

As a potential/current contributor to agileventures
On the upcoming events page
I want to be able to filter to see only upcoming scrums
So that i can find a scrum I am interested in attending

As a potential/current contributor to agileventures
On the upcoming events page
I want to be able to filter to see only upcoming pair programming
So that i can find a pair programming event I am interested in attending
### Less Sure about this one

As a user
On the upcoming events page
I want repeating inactive events to not be present
So that I don't try to attend an event that nobody else is planning to attend
#### Current state of the dropdown.   Many projects.

![image](https://cloud.githubusercontent.com/assets/6599077/19354051/625b732c-9133-11e6-8c13-a8102759c458.png)

**Comment by tansaku** [comment]
@c1505 this is great - I think all of these are strongly desirable.  

Perhaps we should make this an epic ticket, and create individual tickets for each of the ones you mention?

**Comment by c1505** [comment]
Sounds good @tansaku .  Done :)

**Comment by tansaku** [comment]
great work @c1505 - feel free to take the lead on getting the new tickets voted on if you see a gap in #websiteone :-)

**Comment by c1505** [comment]
Thanks @tansaku  :)  .  Should I do that even if it is a ticket I am planning working on and closing soon?  Just weary about overwhelming people with voting.

**Comment by tansaku** [comment]
Good question @c1505 - as a rough guide, ideally we'll get things voted before they're worked on to keep people in the loop.

Of course nothing stops you working on it anyway :-)

You can always say in the slack channel, get guys I want to work on this, is that cool?

I could also start pushing to get more votes from our active members. Or maybe everyone's sick of asynchronous voting and would rather go back to voting in meetings. Although that was a resounding no last time I asked :-)

Hopefully the asynchronous voting bit might speed things along soon. 

Another thing to consider is working on voted tickets first, but if you're really motivated to work on this one, then that's a good reason to just get started on it.

We probably shouldn't have two votes going in parallel (confusing) I'll try to prioritize getting some of your tickets voted on as well.

**Comment by c1505** [comment]
Thanks.  Sounds good.  I am good to work on pretty much whatever.  Mostly came back to this because I thought it could be a quick win in comparison to another one I started looking at and pretty quickly realized I didn't have a full understanding of what was wanted.

**Comment by tansaku** [comment]
@c1505 quick wins are great :-)
