### ISSUE TITLE
[EPIC] Gemfile is currently disorganized and huge

### ISSUE THREAD

**Issue by edmilsonefs** [AgileVentures/WebsiteOne#1369]
**To-do list**:
- [ ] Remove unused or useless gems.
- [ ] Categorize as much as possible.
- [ ] Add comments when applicable.

- [ ] #1411: Gemfile - Remove unused or useless gems .
- [ ] #1412: Gemfile - Categorize as much as possible .
- [ ] #1413: Gemfile - Add comments when applicable .

_Hint: [Eefgilm: A gem for cleaning up your Gemfile](https://github.com/enilsen16/Eefgilm)_

**Comment by edmilsonefs** [comment]
**Current state**:
![gemfile_2016-10-27_websiteone_102716_010210_pm](https://cloud.githubusercontent.com/assets/498938/19775084/0046ff14-9c4e-11e6-93d6-4c25d414c8ae.jpg)

:grimacing:

**Comment by tansaku** [comment]
@edmilsonefs it would be great to get this done - it's relatively straightforward - are you working on this, or should we get someone else on this?

**Comment by edmilsonefs** [comment]
@tansaku Yes, I would like to work here, sorry for the delay. I'm expecting to give a feedback here during this week, if not today. Sorry for the delay. This will help me to review each gem and read about what each one does.

**Comment by tansaku** [comment]
@edmilsonefs can we just run the clearup operation and get that sent in as a PR, and then careful review of each gem can come later in a separate ticket?

**Comment by edmilsonefs** [comment]
**FYI**: 

The following issues were created:
- #1411: Gemfile - Remove unused or useless gems .
- #1412: Gemfile - Categorize as much as possible .
- #1413: Gemfile - Add comments when applicable .

**Comment by edmilsonefs** [comment]
I expect to have #1404 approved and I will leave this task for anyone interested to work on the tasks I created above.

**Comment by tansaku** [comment]
so @edmilsonefs we should unassign from this right? and move back to backlog to be voted on? or this is an epic? can we tick off what we've done?

**Comment by edmilsonefs** [comment]
@tansaku Yes, I tried to unassign from me but you sent it back to me. 

My work was done on the PR https://github.com/AgileVentures/WebsiteOne/pull/1404 : Gemfile cleanup [merged and closed]

This is an EPIC that was broken in the following issues(already mentioned above):
- #1411: Gemfile - Remove unused or useless gems .
- #1412: Gemfile - Categorize as much as possible .
- #1413: Gemfile - Add comments when applicable .

**Comment by tansaku** [comment]
great! - thanks @edmilsonefs
