### ISSUE TITLE
Stub Pivotal Tracker API

### ISSUE THREAD

**Issue by NickSchimek** [AgileVentures/WebsiteOne#2497]
During tests the Pivotal Tracker API is being hit and an exception is being caught to send an email notification. Ideally the API call should be stubbed for tests.

Since the tests are passing regardless if the API call is allowed suggests that there are no tests in place to verify the information received from the call is being displayed. 

`*Update*` - The response is being tested in `features/projects/project_pivotal_stories.feature` and is being stubbed there in the step definition `features/step_definitions/pivotal_steps.rb`, however the `****** URL` line is printed when that feature runs since the print statement happens right before the stub activates. There is nothing wrong with that stub, but the print statement is a bit confusing in the test output. Will update so that the method is stubbed instead of the actual call. All other feature files listed above are hitting the API and should be stubbed or modified to use the existing stub.

The server log when connected to the internet is:
```
****** URL: /projects/853345?fields=description,labels,name,current_velocity,velocity_averaged_over


****** URL: /projects/853345/iterations?scope=current&limit=1&offset=0&fields=velocity,points,effective_points,analytics,stories(url,name,description,story_type,estimate,current_state,requested_by,owners,labels,integration_id,deadline,comments(person(name,id,initials,email,username,kind),text,updated_at,id,created_at,story_id,file_attachments,google_attachment_ids,commit_identifier,commit_type,kind),tasks,transitions,followers,cycle_time_details,accepted_at),team_strength,project_id,length,start,finish
```

And the server log when NOT connected to the web:
```
****** URL: /projects/742821?fields=description,labels,name,current_velocity,velocity_averaged_over

Encountered Error in get: Failed to open TCP connection to www.pivotaltracker.com:443 (getaddrinfo: nodename nor servname provided, or not known)
```

## Ensure the following tests are stubbed:

- [x] features/projects/create_projects.feature:30
- [x] features/projects/create_projects.feature:64
- [x] features/projects/edit_project.feature:36
- [x] features/projects/edit_project.feature:64
- [x] features/projects/project_pivotal_stories.feature:20
- [x] features/projects/show_project.feature:27
- [x] features/projects/show_project.feature:43
- [x] features/projects/connections.feature
- [x] features/public_activity.feature:12
- [x] features/public_activity.feature:26

## Location of where the API call is being made and exception notification is being sent.
app/controllers/projects_controller.rb:101

## Steps to Reproduce
I've noticed when hitting the Projects Show controller when the Project has a Pivotal Tracker link assigned to it.
