### ISSUE TITLE
[EPIC] further improvements to the "past events"/"hangouts" page 

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2930]
amazing work from @dkuku has given us a "past events"/"hangouts" page  with easy to view autoplay videos - this is really outstanding.  There are a few things that could make it even more super-awesome:

* [ ] truncating long event instance titles, e.g. maximum 32 chars, with full title in tooltip
* [x] removing "join" button for events that have finished
* [x] removing the "watch" button completely - do we even need this any more?
* [ ] having premium videos have upsell "please upgrade to view"
  - or even better perhaps allow single view, but then upsell
* [ ] have playing video pop out a little bit (like netflix) - maybe hard to do?
* [ ] have the text of the title, user icon etc. hover over the video (like netflix) to save screen space - maybe difficult?
* [x] have this page called something consistent - at the moment we are confused between:
  - hangouts
  - event instances
  - past events

in different part of the system and interface.  We should try to consolidate on something that's meaningful to the users of the site and accurate, e.g. "Currently live and past events"

for several of the above I'm just thinking about giving more screen real estate to the video so that it's easier to see what's going on.

I'm also thinking that this page is so important maybe it needs it's own high level heading in the site, e.g. video library - maybe it should even be the home page once people are logged in ... not sure - maybe I'm just being silly :-)

**Comment by dkuku** [comment]
I can switch the page title between Currently Live Events, Past Events depending on the state
Disabling the text on the video was possible but this option is disabled from september 25 2018 on youtube :( - maybe possible with some custom js
The buttons are easy to do - maybe I can also get rid of the user avatar - is on top of the video right now ;) 
The full title is available when you click the toggle summary button  - this can be moved to a tooltip
I need to look into the rest

**Comment by dkuku** [comment]
That's how it might look like with only 1 button - might need to have more height. I just used the old css but I don't think it fits. Maybe orange will be better - there will be maybe one or two active ones most of the time.
![cards](https://user-images.githubusercontent.com/904179/49779684-332b3900-fd03-11e8-9b4d-63ba0030db02.png)

**Comment by tansaku** [comment]
great progress @dkuku !  Avatar and title on top of video gives loads of space - wonderful - feel free to push up partial changes - and/or create separate tickets for each different thing :-)

**Comment by tansaku** [comment]
would be great to also change the route/url so it's no longer `/hangouts`, but something like `/event_instances` or even we should have separate urls for `/past_events` and `/live_events`
