### ISSUE TITLE
[EPIC] consolidate all documentation around CONTRIBUTING.md

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#805]
we have legacy documentation in the wiki and in the AV project pages.  Let's pull all of that into the repo (docs dir?) and clear out all other locations with links to the canonical CONTRIBUTING.md start point ...

We have documentation on a number of subjects that needs sorting.  Let's deal with one at a time:
- [x] [getting started/setup](863)
- [x] [mission statement](867) ([GH wiki](https://github.com/AgileVentures/WebsiteOne/wiki/Project-Mission%2C-Goals-and-Vision), [Google Doc](https://docs.google.com/document/d/1KM3QF_iyAd7jkxiSd2hQOWl1vSzwuJbd0inKF6JziTU/edit))
- [x] [development process](869) ([GH wiki](https://github.com/AgileVentures/WebsiteOne/wiki/Project-coordination-outline), [AV wiki](http://www.agileventures.org/projects/websiteone/documents/wso-project-workflow), [GH repo](https://github.com/AgileVentures/WebsiteOne/blob/develop/CONTRIBUTING.md), [AV WSO pitch](http://www.agileventures.org/projects/websiteone#home))
- [ ] [code style and conventions](1146) ([GH wiki](https://github.com/AgileVentures/WebsiteOne/wiki/Code-style-and-conventions))
- [ ] [Current staging servers](1148) ([GH wiki](https://github.com/AgileVentures/WebsiteOne/wiki/Current-staging-servers))
- [ ] [development environment setup](1149) ([GH wiki](https://github.com/AgileVentures/WebsiteOne/wiki/Development-environment-set-up))
- [ ] [thoughts on integrating pair programming with BDD and TDD](1150) ([GH wiki](https://github.com/AgileVentures/WebsiteOne/wiki/Thoughts-on-integrating-Pair-Programming-with-BDD-and-TDD))
- [ ] checking relevance/migrating ([GH wiki](https://github.com/AgileVentures/WebsiteOne/wiki/Adding-title-to-page-view), [GH wiki](https://github.com/AgileVentures/WebsiteOne/wiki/Create-tags-for-project), [wiki](https://github.com/AgileVentures/WebsiteOne/wiki/Current-staging-servers), [GH wiki](https://github.com/AgileVentures/WebsiteOne/wiki/Thoughts-on-integrating-Pair-Programming-with-BDD-and-TDD))

It looks like the wiki has been largely cloned to the AV site or vice versa, so for all the above we need to check both locations
- [ ] review av-site [features request and design and sub-documents](http://www.agileventures.org/projects/websiteone/documents/documentation)
- [ ] review av-site [interesting stuff](http://www.agileventures.org/projects/websiteone/documents/interesting)

**Comment by tansaku** [comment]
refer to https://github.com/AgileVentures/WebsiteOne/wiki/Project-coordination-outline and http://www.agileventures.org/projects/websiteone/documents/how-to-submit-a-pull-request-on-github
