### ISSUE TITLE
[EPIC] Live events should be a first class citizen

### ISSUE THREAD

**Issue by dalupus** [AgileVentures/WebsiteOne#823]
Live events don't really fit into upcoming, or past events.   We need to make them a first class citizen on the site and possibly highlight them better.

**Comment by c1505** [comment]
I can work on this.  

In this situation should live events to be ones that hangouts are currently active on or that are just during the event time?  

For highlighting, I was just thinking about changing how live events appear on the index page.  Maybe some change in color around the event and some text in a to say "Live".  I'll put some screenshots on here with options.  

Any other suggestions for how to highlight them without cluttering up the site too much?  Scrums already show up on a countdown and when live.

**Comment by tansaku** [comment]
hi @c1505 -any updates?  sorry I didn't reply earlier :-(

I think live events should be those that are in the event time - since the hangout API change means we may not easily be able to detect events live status for a while ...

A specific live events end point like code buddies have might make sense

**Comment by c1505** [comment]
Hi @tansaku .  No worries.  I have had a really busy last two weeks and haven't been focused on AgileVentures.  From Monday on, I should be able to put in about 10 hours a week.  

It seems pretty clear that better highlighting on the upcoming events page is a good idea and I will get started on that.  I am less sure about what else would be helpful. 

Is there a benefit of having a separate "live events" endpoint vs. making it clear that live and upcoming are together.  It seems like clicking "live events" and seeing nothing could be demotivating.  I don't have my mind made up either way though.

I noticed that most pairing events for the AgileVentures projects show up in slack, but typically people do not post those on the AgileVentures website.  I am not sure if it is that people don't want to make those as public as the website is or if they just don't want to undertake the effort to make an event.  For people just going to the website, it looks like there is a lot less activity than there actually is.

**Comment by tansaku** [comment]
To the extent the current functionality works we get this "event live now" thing that is shown on the upcoming events page, although anything that started more than 15 minutes ago drops off that page.  The "past events" page does also show the full set of currently live events as long as they are live.

I agree that clicking "live events" and seeing nothing is kind of demotivating.  I think that @dalupus original idea was that there should be a separate endpoint.

I think maybe it would be good to go back to having the events nav element just link to live & upcoming events, and then on that page there could be a separate link to go to finished events - I'm not sure that we need a main nav item that links directly to historic stuff - although some people might want to catch up on recently finished things ...  btw, we had a very interesting experience document from @weedySeaDragon which you should check out - not so much about events, but about the design of our site in general:

[ae__wsd__actual_experience.pdf](https://github.com/AgileVentures/WebsiteOne/files/559282/ae__wsd__actual_experience.pdf)

it might be an idea to mock up a few alternatives for how we imagine the events page to look ...

**Comment by weedySeaDragon** [comment]
I know I'm showing up in the middle of the discussion, but here's my opinion, FWIW:
Seeing **past events** is critical for anyone joining a project or trying to find out more about a project so they can decide whether or not they want to join.  

Also:

As someone new to a project (or considering joining a project so is trying to learn about it)
I want to get up to speed
And watching past meetings/events is a crucial part of getting up to speed on a project
So I want to see a list of past and upcoming events for a project
And the events for a project should be **right there on the project pages.** 

After all, conceptually most events 'belong to' a project, right?  
All of the information about a project should be available on or from the project page(s).  Shouldn't have to go to a different part of the website (_Events_) to get information about a project.

I know this feedback is related to this issue but is sort of tangential to it.  But I wanted to get this info in here because it might affect how you address this one.

**Comment by tansaku** [comment]
thanks @weedySeaDragon - great input - you're right it would be great to show events related to projects on project pages ...

Of course seeing past events only provides value if we have the recordings for them, and the Google hangouts API change just broke that part of the system for us.  Need to get that fixed ...

I also wonder about the value of seeing 50 or 100 previous recordings for a project - I love to data hoard, but I imagine most people would only look at the last one or two, or overview video of a project ...

I guess the question here is if we have "events" in the top nav bar, what should it point to? Maybe this is all something that needs to be part of a bigger site design, but we have limited resources, so maybe the question needs to focus down to what small change can we make to improve the existing site?

Is there some small change that relates to this ticket that makes sense, or should we just move to generating multiple mockups for the new site navigation?

**Comment by tansaku** [comment]
@c1505 any further thoughts any of this?

**Comment by c1505** [comment]
@tansaku  and @weedySeaDragon
I think making it so live events don't drop off the upcoming events page after 15 minutes would be good and also to visually highlight them a bit more than the small amount of text that is currently there.  It doesn't make sense to me to have a button to show the live events on the past events page.  I think that should be removed.  

I don't have a strong opinion either way on having to go through Events to get to past events.  

My only issue with putting the upcoming events on the project page is that it seems like most upcoming events for projects don't make it on the AgileVentures website.  The past events are on there already, but just under the heading videos.

**Comment by weedySeaDragon** [comment]
@tansaku @c1505 I totally agree that live events should be highlighted more.  I think either a lo-fi sketch or, if it's a quick task, just doing some version of this would be good so that folks (us + ...? ) can see something, give feedback and improve on it.    
(I don't have a feel for the typical process here with a task like this.  Some teams would do a lo-fi; some would do a quick iteration and make it live to get feedback.  The feedback is the important thing, IMO.)  

How stuff is organized and displayed on the individual project pages is kind of a separate thing, I think.  The business goals are a bit different (including the fact that each project can organize it's info differently, so the tools and capabilities need to be there, but individuals on projects and move them around much more freely -- right?)   So I'd say that'd be a separate user story in waffle.

**Comment by tansaku** [comment]
@c1505 how are you feeling about this one?  is this something you'd like to work on this week?

**Comment by tansaku** [comment]
I guess I need to do some work on this in order to make progress @c1505 and @weedySeaDragon ... @c1505 perhaps we should find something smaller for you to work on ...

**Comment by tansaku** [comment]
Epic 

* [ ] keep live events on events page #1467
* [ ] on upcoming events, live events should stand out more
* [ ] rename "upcoming events" to "live & upcoming events" and add other language in the page

optional?
* [ ] add live events as one of the dropdown elements and have a separate page for them
* [ ] ensure that project created events appears on event page (auto-create related event?)

**Comment by tansaku** [comment]
```gherkin
As the AV maintainer
So that folks can enjoy and learn in hangouts
I'd like events that are live to be easily discoverable throughout the site
```

**Comment by c1505** [comment]
#1467 is in progress, but the others are back to up for grabs.
