### ISSUE TITLE
do security audit and fix the issues

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#831]
related to #817 - need to get this done before adding security audit to build

Tasks:
- [x] Upgrade GEMS with known security flaws as per bundler:audit #844
- [x] fix injection attack points and other coding issues raised by brakeman's report. #845
- [x] Run the audit reports as part of the CI build once the other issues are fixed. #846

**Comment by freeranger** [comment]
I believe this should be split into three issues:
- one for upgrading GEMS with known security flaws as per brakeman's report
- one for fixing injection attack points and other coding issues raised by bundler:audit.
- one to add running the audit reports as part of the CI build if desired, once the other issues are fixed.

On Project Unify we had some of each and just upgrading the GEMs made all the other issues go away, so in that sense they are not unrelated - though it may not be so easy on a mature, much larger code base like WSO.

My recommendation would be that they are separate issues and that the brakeman gems one is tackled first - they are independently releasable changes which have value in their own right - if we are lucky,  upgrading the GEMs ​*may*​ mean you have less to do on the other one.

**Comment by tansaku** [comment]
that makes sense @freeranger I guess the other alternative is to have the single issue and use markdown todos:

* [ ] upgrade GEMS with known security flaws as per brakeman's report
* [ ] fix injection attack points and other coding issues raised by bundler:audit.
* [ ] running the audit reports as part of the CI build

but each of these might be kind of involved, so breaking them up into separate tickets (linked to this one) is probably the way to go.  Actually we can leave the todo list above and hyperlink that ... :-)

Clearly the whole security audit is a very sensible thing to do, although I might personally prioritize cleaning out the rspec and cucumber STDOUT ( #749 #750 ) and fixing the js instability issue ( #806 ), because both of those are slowing down the testing process, and the latter is affecting the reliability so it will be confusing to see whether the security upgrades are not having functional side effects, does that make sense?

**Comment by freeranger** [comment]
@tansaku I can't edit your comment to hyperlink the todo list but here are the links:
https://github.com/AgileVentures/WebsiteOne/issues/844 - brakeman
https://github.com/AgileVentures/WebsiteOne/issues/845 - bundler:audit
https://github.com/AgileVentures/WebsiteOne/issues/846 - add to ci build

**Comment by tansaku** [comment]
check out how I edited your comment above @freeranger

**Comment by freeranger** [comment]
Ah yes, I could have done that myself (Not edit yours though - I don't have the rights) but then the list is duplicated so I wanted YOURS updated.. Actually never mind, I will update the actual issue description - should have thought of that first ;)

**Comment by diraulo** [comment]
Just a quick note @freeranger. I noticed while working on this that it should be
- [ ] Upgrade GEMS with known security flaws as per **bundler:audit** report
- [ ] fix injection attack points and other coding issues raised by **brakeman**

:wink:

**Comment by freeranger** [comment]
Just keeping you on your toes @diraulo :wink:

**Comment by NickSchimek** [comment]
All tasks were completed. Closing issue.
