### ISSUE TITLE
[EPIC] Smoothing the process of joining a pairing session for edX students (and others)

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#874]
This ticket outlines an EPIC of trying to make it as straightfoward as possible for users to get into a pairing hangout (particularly the edX students)

Here's the series of steps we ask them to go through

1) signing up
  - bug fixes
    - [x] #778
    - [x] #889
  - ideas:  
    - turn back on email registrations?  
    - Spam issues? 
    - [x] Should we remove Gplus? (or is it needed for youtube syncing) #1095
    - [ ] Should we support GitHub login without public emails? #1093
    - [x] Add links on how to make email public in GitHub error message **  here's [how to keep private](https://help.github.com/articles/keeping-your-email-address-private/) #1064

2) browse pairing events 
  - ideas: 
    - big list difficult to browse
      - filtering
        - [x] #949 route for filtering by project
        - [ ] UI for filtering
        - [ ] automate the updating of the list when user selects
      - sorting
      - breaking up the list
      - tagging
      - say how many hours from now an event is 
      - event types shown more clearly
    - provide link to creator
    - [x] provide link to project (#796)
   - display the project name
    - [x] UX: make whole box clickable (#888) (alert UX guy when deployed)
    - add nice features from past events? 
       - mouse over colors the event box
       - showing who is in which hangout ...
  - spend time on improving css, layout, coloring
  - [ ] BUG for Saudi Arabia time zone #1097

3) creation of events 
  - ideas: 
    - new event button not prominent enough
    - always show "new event" button, but prompt login/signup if not logged in
    - event spam
    - [x] setting appropriate defaults (specifically default end for repeats) (#891)
    - [x] remove confusing "End Time in UTC" when not repeating (#893)
    - start time in own time zone (#782)
    - [x] provide helper links e.g. http://www.agileventures.org/events/new?title=Pairing...&project=ADRoR (#908)
    - [x] after editing event you should be returned to event page (#935)
    - [ ] cleaner URL (#988)
    - [x] update images of AV site in pp on air in edx pages
    - [x] allow user to create event in their local timezone #782

4) taking the event live 
  - ideas: 
    - [x] change "Start" to "Host Hangout on Air" (#884)
    - [ ] ability to edit hangout link (#883) 
   - "event live" comes on automatically?  is that a bug or a feature?  did @alejandrobabo have a fix for that? (#902)

5) Notifications
  - ensuring that AV slack is not spammed
    - [x] ensure that agile bot gets correct data on project for event/event_instance (#919)
  - ensuring that gitter is appropriately updated

6) Event show page
 - [x] date bug - wrong year on some events (#897)

7) Event edit page
 - make sure completed edit returns to show page

Other concerns
--------------------

* [ ] finding the event page after event has gone live - relates to past events page?
* having to re-load page to see that event has gone live
* start button still present after event has gone live?

Related Ideas
------

* swap steps 1 and 2?
* [x] clear out old dead pairing events
* administrative interface to make management of events easier (see repeating ones, see level of activity)
* allow filtering by languages
* video to explain process
* supporting text events?
* ensuring all edX hangouts go to the gitter channel (prefer activity stream)

[Video of us developing the epic](https://www.youtube.com/watch?v=r7HRVfm_Ml0)

**Comment by tansaku** [comment]
Could add event creator to event and display link to their profile on AV

**Comment by tansaku** [comment]
Would it make a big difference to have google calendar links? Or be exporting all these events to a Google calendar, of present a Google calendar-like view?

**Comment by freeranger** [comment]
Assuming most people want to join an event rather than start one, I would swap steps one and two - you only need to sign up if you want to host an event, so step 1 is "go see if there is an existing event you could join" and step 2 is "if not, then sign up and create one' or wording to that effect.

As a 169 student, when I come to the events page, I don't really want to see the scrums and other stuff - I am there looking for a pairing session so I would really like to see a pre-filtered list of relevant events.
I am, of course, free to change the filter criteria so I can see others if I wish, but my primary concern is to find a pairing event (or create a new one).

In terms of what I see, I like the idea you explored around breaking the screen up into different days - I would perhaps go with "today", "tomorrow" based on my current timezone of course) and then list day names for the rest of the week, then just go  "next week" and "in the future" if need be?

I don't think it's really necessary to say in 1 hour or two hours since the events are now displayed in my timezone - I know what time it is now so I know that 2pm DST is in 3 hours time or whatever.
One thing you could do perhaps is have a countdown timer to the start of the next event (in your timezone) that matches your filtered criteria?

I would also like to see some more information:
* Who created the event
* What type of event it is: Pair Programming/Scrum/Standup/General Meeting (you only have two types at the moment)
* The topic of the event: "CS169.x HW1", "Issue #123 - The trouble with tribbles", "WSO Weekly Meeting" etc

At the moment seeing 2 meetings for "Pairing on CS169 HW0 Ruby Intro" doesn't tell me much - is it a mistake there are two? Maybe its the same person having a follow up meeting, or maybe it's two completely different ones.
Who is hosting it?  If they aren't there at the meeting time, is it ok for me to kick it off?  If I know who it is then I can look for them on gitter or slack to see if they are around to start it, maybe I can ask them questions in advance (My english is poor, will this be in spanish?  Are you starting from scratch or have you done some already?  What do I need to have done as a prerequisite?)

Having the extra information above, as mandatory fields when a hangout is created, gives me a bit more context - and I think this is useful for anyone, not just MOOC students.

It might also be a good idea from the MOOC page to be able to one-click "Start a hangout now", which will pre-fill all the information (or as much as possible) and get you up and running.
Scenario:
Chatting in bitter about HW1, a few of us want to get into a session.  I go to the homework page in edX for HW1 and click on the "Start a hangout/pairing session now" button - it should have all the necessary contextual information about me and the subject and type of meeting to be able to post a fully populated form to AV to kick off the hangout.

Potential difficulties:
- I have to be signed up to AV first
- SSO from edX to AV
- In the absence of the above, at least being able to pass your username from edX to AV

**Comment by tansaku** [comment]
@touchps said that to start with there were lots of pairing events going on (early HWs) so it was relatively easy to find someone to pair with (active event).  Usually joining something that he saw starting in slack - which most of the time there was only one person waiting - but sometimes there would be 3 or 4 people.  People are then not sure what to do - usually some people just become observers.

Students were often hesitant ("will this thing work or not") - PP was great the first time.  Got some great ideas about different implementations from the other person.  Chances are 50/50 that students might not gain much from the first session.

Later on with HW3, 4 etc. there were fewer events/hangouts, and often the event might not be started or there was no one in the hangout.

Was unclear whether to keep an eye on the list, or focus on slack.  If notified on slack then means likely someone is there.  And generally people will not start each other's events ... people are too polite or don't realise.

**Comment by tansaku** [comment]
@touchps also saying it's confusing with all the AV specific events, and depending on students they may put different amounts of information in the event description about what they want to work on.

**Comment by tansaku** [comment]
closing to be replaced by #1157
