### ISSUE TITLE
EPIC events refactoring

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#898]
Working on the events today we noticed various opportunities for refactoring:

* [ ] EventCreatorService is convoluted and some code in Event should be pulled in
* [ ] Event params and form relation seems strained with some params outside the model
* [ ] The controller specs are testing the validations which should rather me in the model 
* [ ] Jasmine tests are inconsistent
* [ ] need event editing cuke
* [ ] create event cuke is not testing that values are set correctly

**Comment by tansaku** [comment]
For Jasmine fixtures see: https://blog.pivotal.io/pivotal-labs/labs/javascriptspecs-bind-reality, however should we be focusing on fixing as much as we can quickly before moving to something like angular or react or ember?

**Comment by tansaku** [comment]
had a stab at this, but it feels like to make progress what we really need to sort is the way the form is representing the event data ...

**Comment by tansaku** [comment]
close this as we probably don't want this addressed outside of delivering a new feature to client
