### ISSUE TITLE
[EPIC] Premium Membership

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#936]
Pathway 

1) signed up  
- [ ] improve sign up process (#1175)
  - [ ] need to be signed in to pay for premium/premium plus
  - [x] email notification of transaction (#1072)
  - [x] payment page should have more details about what to do next (#1182)
  - [ ] add plan details (link?) to payment complete page (#1190) 

2) upgrade membership option  
- [x] [explanation of associated benefits](http://www.agileventures.org/premium)
- [x] categories of users  (#1122, #1123)
- [x] automatically assign categories (titles?) based on plan subscriptions
- [x] premium won't upgrade cleanly to premiumplus (user has to currently buy one, cancel other) (#1303)
- [x] make upgrade process clear on users page (#1261)
- [x] support upgrade to mob (#1401)
- [ ] support upgrade to all plans (#1524)
- [ ] make pricing clear

3) payment options  
- [x] payment integration  (#754)  
- [x] ability to pay in UK pounds (#1038) 
- [x] support for subscriptions (#1039) 
- [x] live test of payment
- [x] support for premium plus (#1042)
- [x] paypal integration for premium
- [x] paypal integration for other plans
- [x] paypal representation in our system (#1438)
- [x] make paypal payment option more visible (#1435)
- [ ] support for purchasing more pairing hours (#1043)
- [x] sponsorship via paypal (#1436)
- [ ] integrate gocardless (#1776) 
- [ ] support payment in members currency (#1777) 
- [ ] support UK giftaid

4) follow up support and how to access it

5) account management
- [x] change card number #1241
- [ ] cancellation

6) other possibilties
- [ ] general donations page (stripe?)
  - [ ] subscriptions  (variable, fixed options)
  - [ ] one off donations (variable, fixed options)
- [ ] variable levels (or fixed options) of contribution to premium/premiumplus
- [ ] student rates ...
- [ ] swag store - people buy mugs and clothing ... teaser page? see if anybody pre-orders
- [ ] referral bonuses for AV premium signup

It seems that in the first instance that we don't necessarily need to connect the payment framework to the existing user models.  In the long run that might be great - actually being able to flag PRs from premium members might be the critical step, but first up we should try and get a single live payment and deliver services to the presumably small number of initial members.

Allowing people to sign up for the premiumplus plan should probably then be priority over further integration with the rest of the system until it's clear that further integration is actually necessary ...

**Comment by ModdedGamers** [comment]
Any way we could add ways to pay in cryptocurrency?

**Comment by tansaku** [comment]
@ModdedGamers yeah, we're just looking at that with the https://gitcoin.co folks

**Comment by ModdedGamers** [comment]
Cool. Thanks!

**Comment by mattlindsey** [comment]
Closing old issues.  Since premium membership don't exist at the moment, we might need a new epic/issues for that.
